---
version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: $SLACK_HOOK_URL
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: $SLACK_IDENTIFIER
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: $SLACK_CHANNEL
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: ":whale:"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
