version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    network_mode: 'host'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ENABLE_IPV6=true
      - DISABLE_ACCESS_LOGS=true
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './data/nginx-proxy-certs:/etc/nginx/certs:ro'
      - 'nginx-config:/etc/nginx/conf.d'
      - './data/nginx/vhost.d:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - './data/nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    networks:
      - default
    environment:
      DEFAULT_EMAIL: $EMAIL
      #- DEBUG=true
    volumes:
      - './data/nginx-proxy-certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'nginx-config:/etc/nginx/conf.d'
      - './data/nginx/vhost.d:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'

volumes:
  nginx-config:
  #nginx-vhosts:
  nginx-webroot:

networks:
  default:
    name: nginx-proxy
