version: '3.5'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    environment:
      - ENABLE_IPV6=true
      #- DISABLE_ACCESS_LOGS=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/nginx-proxy-certs:/etc/nginx/certs:ro
      - 'nginx-config:/etc/nginx/conf.d'
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-webroot:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./data/nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ${HTPASSWD_PATH}:/etc/nginx/htpasswd:ro

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    networks:
      - default
    environment:
      DEFAULT_EMAIL: $EMAIL
      #- DEBUG=true
    volumes:
      - ./data/nginx-proxy-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-config:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-webroot:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - acme:/etc/acme.sh

volumes:
  nginx-config:
  nginx-vhosts:
  nginx-webroot:
  acme:
  dhparam:

networks:
  default:
    external:
      name: nginx-proxy
